#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - copy:
        content: |
          # vars
          {{ vars | to_nice_yaml }}
          # group_names
          {{ group_names | to_nice_yaml }}
          # groups
          {{ groups | to_nice_yaml }}
          # hostvars
          {{ hostvars | to_nice_yaml }}
        dest: '{{ playbook_dir ~ "/tmp/dump.yml" }}'
