#!/usr/bin/env ansible-playbook
---

- hosts: all
  gather_facts: False

  tasks:
    
    - include: tasks/assert-desktop.yml
    - include: tasks/assert-local-group.yml

    - tags: get
      vars: &deb
        debdir: /usr/local/dist
        deb: skypeforlinux-64.deb
        url: https://go.skype.com/{{ deb }}
      when: &gdebi use_apt is not defined
      block:
        - debug: { msg: 'get url {{ url }} to {{ debdir }}/{{ deb }}' }
        - file:
            path: '{{ debdir }}'
            group: staff
            mode: g+ws
          become: True
        - get_url:
            url: '{{ url }}'
            dest: '{{ debdir }}/{{ deb }}'

    - tags: gdebi
      vars:
        <<: *deb
        bin: /usr/bin/skypeforlinux
      when: *gdebi
      become: True
      block:
        - debug: { msg: 'install {{ debdir }}/{{ deb }} using gdebi' }
        - apt: { name: gdebi }
        - command: gdebi -n {{ debdir }}/{{ deb }}
          args: { creates: '{{ bin }}' }
      
    - tags: apt
      vars: *deb
      when: use_apt is defined
      block:
        - debug: { msg: 'install {{ url }}' }
        - apt: { deb: '{{ url }}' }
          become: True

    - apt: { name: libcanberra-gtk-module }
      become: True
