#!/usr/bin/env ansible-playbook
---

- name: Install duplicity
  hosts: all

  vars:
    aname: duplicity
    serie: 0.7
    version: 18.2
    base: '{{ aname }}-{{ serie }}.{{ version }}'
    targz: '{{ base }}.tar.gz'
    urlt: >
      https://code.launchpad.net/{{ aname }}/
      {{ serie }}-series/{{ serie }}.{{ version }}/
      +download/{{ targz }}
    url: '{{ urlt | replace(" ", "") }}'
    local: /usr/local
    tmp: '{{ local }}/tmp'
    src: '{{ local }}/src'
    bin: '{{ local }}/bin'

  tasks:
    - name: Get release from official site
      environment: '{{ proxy_env | default({}) }}'
      get_url:
        url: '{{ url }}'
        dest: '{{ playbook_dir }}/tmp'
      delegate_to: localhost

    - name: Extract tar
      unarchive:
        src: tmp/{{ targz }}
        dest: '{{ local }}/src'
        extra_opts: --no-same-owner
        creates: '{{ src }}/{{ base }}'
      become: True

    - name: Install deps
      apt:
        name: [ gcc, python-dev, python-setuptools, python-fasteners, librsync-dev ]
      become: True

    - name: Install
      command: python setup.py install --prefix={{ local }} --record files.txt
      args:
        chdir: '{{ src }}/{{ base }}'
        creates: '{{ bin }}/{{ aname }}'
      become: True
