---

- src: https://github.com/thydel/ar-regenerate-host-keys.git
  name: regenerate-host-keys
  version: master

- src: geerlingguy.ansible-role-packer
- src: geerlingguy.packer-debian

- src: https://github.com/tompscanlan/ansible-role-vmware-workstation.git
  name: vmware-workstation

- src: jdauphant.vagrant

- src: https://github.com/thydel/ar-sudoersd.git
  name: sudoersd
  version: master

- src: willshersystems.sshd
  name: sshd
  version: master

- src: paluh.augeas
  name: augeas
  version: master
