#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  gather_facts: False

  vars:
    service: user-ssh-agent

  tasks:

    - vars:
        dir: |-
          {{ lookup('env','HOME') + '/.config/systemd/user' }}
      block:
        - file:
            path: '{{ dir }}'
            state: directory
        - copy:
            dest: '{{ dir }}/{{ service }}.service'
            content: |
              [Unit]
              Description=Local SSH key agent
              
              [Service]
              Type=simple
              Environment=SSH_AUTH_SOCK=%t/{{ service }}.socket
              ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK -t 1d
              
              [Install]
              WantedBy=default.target
    - command: systemctl --user --no-legend list-unit-files user-ssh-agent.service
      changed_when: False
      register: systemctl
    - debug: { var: systemctl }
      when: False
    - systemd:
        name: '{{ service }}'
        scope: user
        enabled: True
      vars:
        txt: systemctl --user enable user-ssh-agent
    - systemd:
        name: '{{ service }}'
        scope: user
        state: started
      vars:
        txt: systemctl --user start user-ssh-agent
    - meta: end_play
