---

- tags: assert_desktop
  vars:
    desktops:
      - /usr/bin/gnome-session
      - /usr/bin/mate-session
    a_desktop: 1
  block:
    - debug: { verbosity: 1, msg: fail if not on a dektop node }
    - stat: { path: '{{ desktops[a_desktop] }}' }
      register: desktop
    - assert: { that: desktop.stat.exists is defined and desktop.stat.exists }
