---

- tags: assert_local_group
  vars: { group: staff }
  block:
    - debug: { verbosity: 1, msg: 'fail if invoking user ({{ ansible_ssh_user }}) not in group {{ group }}' }
    - getent:
        database: group
        key: '{{ group }}'
        split: ':'
    - set_fact:
        users: |
          {{ getent_group[group] | difference([0, 1] | map('extract', getent_group[group]) | list) }}
    - assert:
        that: users | intersect([ ansible_ssh_user ]) | length > 0
